name: external_storage_example
description: "Demonstrates how to use the external_storage plugin."
publish_to: 'none'

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  external_storage:
    path: ../

  path: ^1.9.0
  mockito: ^5.4.4
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.1
  open_file: ^3.5.10
  mime: ^2.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
